name: Build
on: [push, pull_request]
jobs:
  build:
    runs-on: ubuntu-latest
    if: "! contains(github.event.head_commit.message, '[skip ci]')"
    steps:
    - uses: actions/checkout@v1
    - name: Cache nimble
      id: cache-nimble
      uses: actions/cache@v1
      with:
        path: ~/.nimble
        key: ${{ runner.os }}-nimble
    - uses: jiro4989/setup-nim-action@v1
      with:
        nim-version: '1.4.0'
    - name: Test nimpylib
      run: nimble test
    - name: Update GitHub Pages HTML documentation
      uses: EndBug/add-and-commit@v5  # https://github.com/EndBug/add-and-commit
      with:
        add: 'docs --force'
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
